### ISSUE TITLE
Website has a Ui bug 

### ISSUE THREAD

**Issue by dipakpatil025** [BlackTimber-Labs/HacktoberFest2021#46]
![image](https://user-images.githubusercontent.com/59409363/135895578-09ab1f82-643d-4f93-a3d6-ba963dcb3675.png)
![image](https://user-images.githubusercontent.com/59409363/135895627-8df1089b-3364-4582-821c-264803eaa95e.png)

**Comment by dipakpatil025** [comment]
1] Text not visible property
2] images not rendered properly

**Comment by kumarsomeshunos** [comment]
both issues now patched

**Comment by HimanshiGupta010** [comment]
Hello,
I want to contribute as a contributer in hacktoberfest 2021.
So please assign me this issue.
