### ISSUE TITLE
ISSUE : Nav bar it not fixed.

### ISSUE THREAD

**Issue by saswatsamal** [BlackTimber-Labs/HacktoberFest2021#53]
Hey 👋

I found that the website's navbar is not always fixed at the top. So whenever I need the use of the navbar, I need to scroll back to the top again.
So, fixing the navbar to the top will make the user experience better.
I can work on this, please assign it to me.

**Comment by bidishaMondal7** [comment]
Hi,
would like to contribute if the issue is up.  Can you please assign to me?

**Comment by bidishaMondal7** [comment]
Pull Req - https://github.com/BlackTimber-Labs/HacktoberFest2021/pull/56

**Comment by saswatsamal** [comment]
Fixed #57
