### ISSUE TITLE
make website mobile responsive

### ISSUE THREAD

**Issue by meixinchoy** [BlackTimber-Labs/HacktoberFest2021#6]
Hi, I would love to contribute by making the website mobile responsive.

**Comment by dipakpatil025** [comment]
hello, i can do it assign me this task .😊

**Comment by dipakpatil025** [comment]
@meixinchoy all the bugs ans issues are fixed , checkout #32 PR

**Comment by RITEKROUNAK** [comment]
you can continue with work without assigning.
